web:
  image: pinuaga/ubuntu_php_mysql
  command: php -S 0.0.0.0:8000 -t /var/www/html
  links:
    - db
  ports:
    - "8000:8000"
  volumes:
    - .:/var/www/html
db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: root
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: myapp
